import { DocumentGeneratorService } from './services/document-generator.service';
import { ExcelStyles } from './services/excel-builder.service';

describe('DocumentGeneratorService', () => {
  it('creates excel builder and produces xlsx buffer', async () => {
    const service = new DocumentGeneratorService({});
    const buffer = await service
      .createExcelBuilder()
      .addSheet({
        name: 'Summary',
        columns: [
          { header: 'Label', key: 'label', width: 20 },
          { header: 'Amount', key: 'amount', width: 15, style: ExcelStyles.rupeeAmountStyle },
        ],
      })
      .addRows([{ label: 'Total', amount: 1000 }])
      .endSheet()
      .build();

    expect(Buffer.isBuffer(buffer)).toBe(true);
    expect(buffer.length).toBeGreaterThan(100);
    expect(buffer.subarray(0, 2).toString()).toBe('PK');
  });

  it('creates pdf builder and produces pdf buffer', async () => {
    const service = new DocumentGeneratorService({});
    const buffer = await service
      .createPdfBuilder('pdfkit')
      .addSection('Intro')
      .addHeading('Test Report', 1)
      .addParagraph('Generated by unit test.')
      .endSection()
      .build();

    expect(Buffer.isBuffer(buffer)).toBe(true);
    expect(buffer.subarray(0, 4).toString()).toBe('%PDF');
  });
});
